name: path-filter
on:
  push:
    paths:
      - '.github/workflows/part1/*'
      - '!.github/workflows/part1/push.yml'

jobs:
  path-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo hello kelly!
