name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: '이름 적어요 빨리.'
        required: true
        default: 'kelly-kelly'
        type: string
      enviroment:
        description: '너의 환경은...?'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world.
          echo good bye action.
      - name: echo inputs
        run: |
          echo ${{ inputs.name }}
          echo ${{ inputs.enviroment }}
